# Welcome to Jekyll!
# Site settings

name: Saif Pirjade
title: Saif Pirjade | Full Stack Developer
email: saif.pirjade@gmail.com
description: specialized in backend and frontend development for complex scalable web apps.
base_url: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sayeaf.me/" # the base hostname & protocol for your site, e.g. http://example.com
cover: https://sayeaf.me/assets/metaimage.png
resume: https://sayeaf.me/assets/Resume_me.pdf
twitter_username: saifpirjade
github_username:  saifpirjade
social:
  - title: email
    url: mailto:saif.pirjade@gmail.com
  - title: github
    url: https://github.com/saifpirjade
  - title: facebook
    url: https://www.facebook.com/saif.pirjade

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - '*.gemspec'
  - 'README.md'
  - 'package.json'

 